# Spring
spring:
  application:
    name: fae-team-1-service-ms
  profiles:
    active: local
  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  # JSON Pretty Print
  jackson:
    serialization:
      indent-output: true
    deserialization:
      accept-empty-array-as-null-object: true
  kafka:
    group-id: "fae-team-1-service"

# Server
server:
  port: 8080
  compression.enabled: true
  compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    context-path: /team-1
# Kafka-topic
product.topic: product

# swagger-ui
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    displayRequestDuration: true
    tagsSorter: alpha
